In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("imageMNIST.csv", header=None, low_memory=False)
df_y = pd.read_csv("labelMNIST.csv", header=None)

def change_type(x):
    if(isinstance(x, int)):
        return float(x)
    elif(isinstance(x, str)):
        return float(x.replace(",", "."))

df = df.applymap(change_type)

In [3]:
#sigmoide
def sigmoid(z):
    g = (1 + np.exp(-z))**(-1)
    return g

In [4]:
def sigmoidGradient(z):
    sigmoid = 1/(1+np.exp(-z))
    return sigmoid*(1-sigmoid)

In [5]:
rand_index = []
for i in range(50):
    rand_index.append(random.randint(0,df.shape[0]))

X = df.iloc[rand_index].values
m,n = X.shape

y = df_y.iloc[rand_index].values
df_encoded = pd.get_dummies(df_y[0], prefix='digit')

In [6]:
X = df.values
m,n = X.shape

In [7]:
y = df_y.values

In [8]:
def check_grad(X,y,theta,size_in,size_hidden,size_out, Lambda):
    epsolon = 1e-4
    theta1 = theta[0]
    theta2 = theta[1]
    
#     theta_p1 = theta1+epsolon 
#     theta_m1 = theta1-epsolon
    theta_p1 = np.vstack(theta1+epsolon, theta2)
    theta_m1 = np.vstack(theta1-epsolon, theta2)
    
    theta_p2 = np.vstack(theta1, theta2+epsolon)
    theta_m2 = np.vstack(theta1, theta2-epsolon)
    
    J_p1, grad1, grad2, reg_J_p1, grad1_reg, grad2_reg = costFunction(X,y,theta_p1,size_in,size_hidden,size_out, Lambda)
    J_m1, grad1, grad2, reg_J_m1, grad1_reg, grad2_reg = costFunction(X,y,theta_m1,size_in,size_hidden,size_out, Lambda)
    
    J_p2, grad1, grad2, reg_J_p2, grad1_reg, grad2_reg = costFunction(X,y,theta_p2,size_in,size_hidden,size_out, Lambda)
    J_m2, grad1, grad2, reg_J_m2, grad1_reg, grad2_reg = costFunction(X,y,theta_m2,size_in,size_hidden,size_out, Lambda)
    
    J, grad1, grad2, reg_J, grad1_reg, grad2_reg = costFunction(X,y,theta,size_in,size_hidden,size_out, Lambda)
    
    check_delta1 = (J_p1-J_m1) / (2*epsolon)
    check_delta2 = (J_p2-J_m2) / (2*epsolon)
    
    check_delta1_reg = (reg_J_p1-reg_J_m1) / (2*epsolon)
    check_delta2_reg = (reg_J_p2-reg_J_m2) / (2*epsolon)
    
    diff1 = np.abs(check_delta1 - grad1)
    diff2 = np.abs(check_delta2 - grad2)
    diff1_reg = np.abs(check_delta1_reg - grad1_reg)
    diff2_reg = np.abs(check_delta2_reg - grad2_reg)
    
    return (diff1, diff2, diff1_reg, diff2_reg)

In [9]:
def costFunction(X,y,theta,size_in,size_hidden,size_out,Lambda,num_hiden_layers):
    theta1 = theta[0]
    theta2 = theta[1]
    
    m = X.shape[0]
    J = 0
#     X = np.hstack((np.ones((m,1)),X))
    y_onehot = np.zeros((m,size_out))
    a = [[]]
    a[0] = sigmoid(X.dot(theta[0].T)) #antigo a1 
    a[0] = np.hstack((np.ones((m,1)),a[0]))
    
    for i in range(1,num_hiden_layers+1):
        a[i] = sigmoid(a[i-1].dot(theta[i].T)) 
    
    y_onehot = np.zeros((y.size, y.max()+1))
    y_onehot[np.arange(y.size),y.flatten()] = 1
    y_onehot = y_onehot[:,1:]
    
    for j in range(size_out):
        J = J + sum(-y_onehot[:,j]*np.log(a[num_hiden_layers][:,j])-(1-y_onehot[:,j])*np.log(1-a[num_hiden_layers][:,j]))
        
    J = 1/m*J
    
    reg_J = 0
    for arr in theta:
        reg_J  += (np.sum(arr[1:]**2))
    reg_J = J + Lambda/(2*m)*reg_J
                                 
    grad = [[]]
    for i in range (0,num_hiden_layers+1):
        grad[i] = np.zeros((theta[i].shape))

                                 
    for i in range(m):
        an_i = [[]]
        xi = X[i,:]
        a1i = a1[i,:]
        a2i = a2[i,:]
        d_inverso = [[]]
        d_inverso[0] = a[num_hiden_layers+1] - y_onehot[i,:]
        for j in range(1,num_hiden_layers+1):
            d_inverso[j] = theta[num_hiden_layers+1-j].T.dot(d_inverso[j-1].T) * sigmoidGradient(np.hstack((1,xi.dot(num_hiden_layers-j))))
        d = d_inverso.reverse()
        for j in range(0,num_hiden_layers)
            if(i == 0):
                grad[j] = d[j][1:][:,np.newaxis].dot(xi[:,np.newaxis].T)
            else:
                grad[j] = grad[j] + d[j][1:][:,np.newaxis].dot(xi[:,np.newaxis].T)
        if(i == 0):
            grad[num_hiden_layers] = d[num_hiden_layers].T[:,np.newaxis].dot(a1i[:,np.newaxis].T)
        grad2 = grad2 + d2.T[:,np.newaxis].dot(a1i[:,np.newaxis].T)
                                 
    grad1 = grad1/m
    grad2 = grad2/m
                                 
    grad1_reg = grad1 + (Lambda/m)*np.hstack((np.zeros((theta1.shape[0],1)),theta1[:,1:]))
    grad2_reg = grad2 + (Lambda/m)*np.hstack((np.zeros((theta2.shape[0],1)),theta2[:,1:]))
                                 
    return J,grad1,grad2,reg_J,grad1_reg,grad2_reg

SyntaxError: invalid syntax (<ipython-input-9-ee4ec49ddac0>, line 45)

In [ ]:
##peguei do site amigo https://prateekvishnu.medium.com/xavier-and-he-normal-he-et-al-initialization-8e3d7a087528
def randInitializeXavier(size_in, size_out):
    w = np.random.randn(size_out,size_in)*np.sqrt(1/size_in) 
    return w

In [ ]:
def gradientDescent(X,y,alpha,n_iter,Lambda,hidden_layer_sizes):
    
    input_layer_size = X.shape[1]
    num_labels = len(set(y.flatten()))
    m = len(y)
    
#     sizes of input
    inputs_sizes = [input_layer_size] + hidden_layer_sizes
    output_sizes = hidden_layer_sizes + [num_labels]

# initialize weights
    theta = []
    for i in range(len(hidden_layer_sizes)+1):
        theta.append(randInitializeXavier(inputs_sizes[i], output_sizes[i]))
        
    J_history = []
    
    for i in range(n_iter):
        cost, grad, cost_reg, grad_reg = costFunction(X,y,theta,input_layer_size,hidden_layer_size,num_labels,Lambda)
        theta1 = theta1 - (alpha*grad1)
        theta2 = theta2 - (alpha*grad2)
        J_history.append(cost)
        
    nn_paramsFinal = np.array([theta1,theta2], dtype=object)
    return nn_paramsFinal, J_history

In [ ]:
def prediction(X,theta,hidden_layers_sizes):
    m = X.shape[0]
    X = np.hstack((np.ones((m,1)),X))
    
    inn = X
    for i in range(len(hidden_layers_sizes)):
        out = sigmoid(inn.dot(theta[i].T))
        out = np.hstack((np.ones((m,1)),out))
        inn = out
    
    return np.argmax(out,axis=1)+1

In [75]:
m = df.shape[0]
samples = 20
rand_index = random.sample([i for i in range(m)], k=samples)

X = df.iloc[rand_index].values
y = df_y.iloc[rand_index].values

In [76]:
alpha = 0.01
n_iter = 100
Lambda = 1
hidden_layers_sizes = [10, 20]

theta,J_history = gradientDescent(X,y,alpha,n_iter,Lambda,hidden_layers_sizes)

pred = prediction(X,theta,hidden_layers_sizes)
print("Training Set Accuracy:", np.sum(np.array(pred)==np.array(y))/len(y)*100,"%")

NameError: name 'costFunction' is not defined

In [55]:
df_y

0
0     10
1     10
2     10
3     10
4     10
...   ..
4995   9
4996   9
4997   9
4998   9
4999   9

[5000 rows x 1 columns]

In [45]:
a = np.array([1,2,3,4,1])
b = np.array([1,2,4,3])
len(set(a))

4

In [35]:
[a[i]==b[i] for i in range(len(a))]

[True, True, False, False]

In [21]:
a = [10,2,4] + [1]
# a.insert(len(a),10)

In [27]:
a = [1,1,1,2,1,1,1]

In [28]:
len(set(a))

2

In [120]:
np.append(theta1.flatten(),theta2.flatten()).shape

(10250,)

In [216]:
a = np.array([1, 4, 5])
b = np.array([8,5])

numpy.ndarray

In [12]:
y10 = np.zeros((10,10))
y = df_y[-10:].values
for i in range(1,10+1):
    y10[:,i-1][:,np.newaxis] = np.where(y==i,1,0)

In [80]:
a = np.array([1,2,3])
b = np.array([4,2,3])

In [90]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 2, 3]])

In [14]:
y_onehot = np.zeros((y.size, y.max()+1))
y_onehot[np.arange(y.size),y] = 1

In [15]:
y_onehot

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
for digit in range(1,11):
    y = df_encoded["digit_" + str(digit)].values.reshape(m,1)

In [17]:
df_encoded.values

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]], dtype=uint8)

In [63]:
y = np.array([[1,2,3,4],[5,6,7,8]])

In [70]:
y.shape

(2, 4)

In [69]:
y.T.shape

(4, 2)

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

NameError: name 'shape' is not defined

In [38]:
y_onehot = np.zeros((y.size, y.max()+1))
y_onehot[np.arange(y.size),y] = 1

In [39]:
y_onehot

array([[0., 1., 1.],
       [0., 1., 1.]])

In [44]:
y = np.array([[1],[2]])
y = y.flatten()
y10 = np.zeros((y.size,5))
for i in range(1,5+1):
    y10[:,i-1][:,np.newaxis] = np.where(y==i,1,0)

ValueError: could not broadcast input array from shape (2) into shape (2,1)

In [45]:
y = np.array([[1],[2]])
y_onehot = np.zeros((y.size, y.max()+1))
y_onehot[np.arange(y.size),y.flatten()] = 1

In [46]:
y_onehot

array([[0., 1., 0.],
       [0., 0., 1.]])

In [79]:
for l in range(len([1,2,3,4,5]) - 2, -1, -1):
    print(l)

3
2
1
0


In [18]:
theta =np.array([ np.array([1,1]), np.array([3,4,5]), np.array([6,5])]) 

/home/julia/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([array([3, 4, 5]), array([6, 5])], dtype=object)

In [35]:
s = 0
for arr in theta:
    s += (np.sum(arr[1:]**2))
print(s)



67


In [46]:
grad = [[]]
grad[4] = 1

IndexError: list assignment index out of range

In [42]:
grad

[1]